### ISSUE TITLE
Tutorials doesn't work out of the box

### ISSUE THREAD

**Issue by ibiBgOR** [angularjs-de/angularjs-tutorial-code#1]
I recently faced the Problem that the two way databinding tutorial test code doesn't work properly. 
After some reading of the code I just copied I noticed, that there is some missing "http:" before the urls. After inserting them all worked properly. 
Plesse add "http:" to all urls where it is missing to be sure that the url is correct and valid.

**Comment by gitviola** [comment]
Hey @ibiBgOR, I've now added `https:` to every url
